language: bash

services:
  - docker

env:
  matrix:
    - GOOS=linux GOARCH=amd64
    - GOOS=linux GOARCH=arm
    - GOOS=linux GOARCH=arm64
    - GOOS=darwin GOARCH=amd64
    - GOOS=windows GOARCH=amd64

script:
  - set -e
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release"

before_deploy:
  - make package
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - "wodby-${GOOS}-${GOARCH}.tar.gz"
  on:
    tags: true
