language: go

services:
  - docker

env:
  global:
    - DEP_VERSION=0.4.1
    - VERSION="${TRAVIS_TAG}"
    - TAG="${VERSION:-latest}"
  matrix:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=arm
    - GIMME_OS=linux GIMME_ARCH=arm64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=amd64

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - set -e
  - dep ensure
  - make
  - make test

after_success:
  - ./release

before_deploy:
  - make package
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - bin/wodby-*.tar.gz
  on:
    tags: true
