language: go

services:
  - docker

env:
  global:
    - DEP_VERSION=0.4.1
    - TAG=latest
  matrix:
    - GOOS=linux GOARCH=amd64
    - GOOS=linux GOARCH=arm
    - GOOS=linux GOARCH=arm64
    - GOOS=darwin GOARCH=amd64
    - GOOS=windows GOARCH=amd64

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - set -e
  - dep ensure
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release"

before_deploy:
  - make package
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - bin/wodby-*.tar.gz
  on:
    tags: true
